# Generated by Django 4.1.3 on 2022-11-09 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=datetime.datetime(2022, 11, 9, 10, 4, 10, 164784, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
